/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MCSUiModule extends org.osate.xtext.aadl2.mcs.ui.AbstractMCSUiModule {
	public MCSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
