/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs.scoping

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class MCSScopeProvider extends org.osate.xtext.aadl2.scoping.Aadl2ScopeProvider {

}
