/**
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs.ui.quickfix;

import org.osate.xtext.aadl2.ui.quickfix.Aadl2QuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class MCSQuickfixProvider extends Aadl2QuickfixProvider {
}
