/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MCSUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.osate.xtext.aadl2.mcs.ui.internal.MCSActivator.getInstance().getInjector("org.osate.xtext.aadl2.mcs.MCS");
	}
	
}
