/*
* generated by Xtext
*/
package org.osate.xtext.aadl2.mcs.validation;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class MCSJavaValidator extends org.osate.xtext.aadl2.mcs.validation.AbstractMCSJavaValidator {

//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
//		}
//	}
}
