/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.osate.xtext.aadl2.mcs.services.MCSGrammarAccess;

public class MCSParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MCSGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.osate.xtext.aadl2.mcs.parser.antlr.internal.InternalMCSParser createParser(XtextTokenStream stream) {
		return new org.osate.xtext.aadl2.mcs.parser.antlr.internal.InternalMCSParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "MCSGrammarRoot";
	}
	
	public MCSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MCSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
