/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MCSRuntimeModule extends org.osate.xtext.aadl2.mcs.AbstractMCSRuntimeModule {

}
