/*
* generated by Xtext
*/
package org.osate.xtext.aadl2.mcs;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MCSStandaloneSetup extends MCSStandaloneSetupGenerated{

	public static void doSetup() {
		new MCSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

