/**
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs.scoping;

import org.osate.xtext.aadl2.scoping.Aadl2ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class MCSScopeProvider extends Aadl2ScopeProvider {
}
