/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.osate.xtext.aadl2.mcs.ui.internal.MCSActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MCSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MCSActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MCSActivator.getInstance().getInjector(MCSActivator.ORG_OSATE_XTEXT_AADL2_MCS_MCS);
	}
	
}
