/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.mcs.ui.contentassist

import org.osate.xtext.aadl2.mcs.ui.contentassist.AbstractMCSProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MCSProposalProvider extends AbstractMCSProposalProvider {
}
